# all podcast metadata (list of dicts)
# one useful resource: https://github.com/foorilla/allainews_sources

PODCASTS = [
    {
    # interview style -------------------------------------
        "id": "dataframed",
        "name": "DataFramed",
        "description": "Interviews with data professionals and leaders on AI and data topics",
        "category": "interview",
        "release_schedule": "Weekly on Monday",
        "hosts": ["Richie Cotton"],
        "rss_feed": "https://feeds.captivate.fm/dataframed/",
    },
    {
        "id": "how_i_ai",
        "name": "How I AI",
        "description": "Interviews with diverse guests (moms, CTOs, etc.) on how they personally use AI",
        "category": "interview",
        "release_schedule": "Weekly on Monday",
        "hosts": ["Claire Vo"],
        "rss_feed": "https://anchor.fm/s/1035b1568/podcast/rss",
    },
    {
        "id": "practical_ai",
        "name": "Practical AI",
        "description": "Interviews with AI professionals on a wide range of AI topics",
        "category": "interview",
        "release_schedule": "Weekly ish",
        "hosts": ["Chris Benson", "Daniel Whitenack"],
        "rss_feed": "https://changelog.com/practicalai/feed",
    },
    {
        "id": "women_in_data",
        "name": "Women in Data Podcast",
        "description": "Interviews with women in data on careers, being a woman in the field, and data & AI tips",
        "category": "interview",
        "release_schedule": "Biweekly",
        "hosts": ["Karen Jean-Francois"],
        "rss_feed": "https://feed.podbean.com/womenindata/feed.xml",
    },
    {
        "id": "twiml",
        "name": "The TWIML AI Podcast",
        "description": "Deep-dive interviews with AI/ML researchers and practitioners on cutting-edge topics",
        "category": "interview",
        "release_schedule": "Biweekly ish",
        "hosts": ["Sam Charrington"],
        "rss_feed": "https://twimlai.com/feed",
    },
    {
        "id": "super_data_science",
        "name": "Super Data Science: ML & AI Podcast with Jon Krohn",
        "description": "ML, AI, and data professionals on tools, techniques, and careers",
        "category": "interview",
        "release_schedule": "Weekly on Tuesday, Friday (short)",
        "hosts": ["Jon Krohn"],
        "rss_feed": "https://feeds.megaphone.fm/SUPERDATASCIENCEPTYLTD9836501887",
    },
    {
        "id": "latent_space",
        "name": "Latent Space: The AI Engineer Podcast",
        "description": "Technical deep dives with AI researchers and builders on models, agents, infra, and tools",
        "category": "interview",
        "release_schedule": "A couple times a week",
        "hosts": ["Shawn Wang", "Alessio Fanelli"],
        "rss_feed": "https://rss.flightcast.com/vgnxzgiwwzwke85ym53fjnzu",
    },
    {
        "id": "gradient_dissent",
        "name": "Gradient Dissent: Conversations on AI",
        "description": "Interviews with AI industry leaders on deploying ML in production, hosted by Weights & Biases",
        "category": "interview",
        "release_schedule": "Biweekly ish",
        "hosts": ["Lukas Biewald"],
        "rss_feed": "https://feeds.captivate.fm/gradient-dissent/",
    },
    {
        "id": "no_priors",
        "name": "No Priors: Artificial Intelligence",
        "description": "Interviews with top AI engineers, researchers and founders on AGI, market disruption, and the future of AI",
        "category": "interview",
        "release_schedule": "Weekly on Thursday",
        "hosts": ["Sarah Guo", "Elad Gil"],
        "rss_feed": "https://feeds.megaphone.fm/nopriors",
    },
    {
        "id": "mlst",
        "name": "Machine Learning Street Talk",
        "description": "Deep academic paper discussions and research interviews with ML researchers and PhDs",
        "category": "interview",
        "release_schedule": "Biweekly ish",
        "hosts": ["Tim Scarfe", "Keith Duggar"],
        "rss_feed": "https://anchor.fm/s/1e4a0eac/podcast/rss",
    },
    {
        "id": "vanishing_gradients",
        "name": "Vanishing Gradients",
        "description": "Deep dives into machine learning research and practice",
        "category": "interview",
        "hosts": ["Hugo Bowne-Anderson"],
        "rss_feed": "https://api.substack.com/feed/podcast/2632531.rss",
    },
    {
        "id": "training_data",
        "name": "Training Data",
        "description": "Conversations about AI, data, and the people building it",
        "category": "interview",
        "hosts": ["Sonya Huang", "Pat Grady"],
        "rss_feed": "https://feeds.megaphone.fm/trainingdata",
    },
    {
        "id": "mixture_of_experts",
        "name": "Mixture of Experts",
        "description": "IBM's podcast on AI research and enterprise applications",
        "category": "interview",
        "hosts": ["Tim Hwang"],
        "rss_feed": "https://feeds.casted.us/95/Mixture-of-Experts-0d38e236/feed",
    },
    {
        "id": "mad_podcast",
        "name": "The MAD Podcast",
        "description": "Machine learning, AI and data discussions",
        "category": "interview",
        "hosts": ["Matt Turck"],
        "rss_feed": "https://anchor.fm/s/f2ee4948/podcast/rss",
    },
    {
        "id": "high_signal",
        "name": "High Signal",
        "description": "Cutting through AI hype with practical signal",
        "category": "interview",
        "hosts": ["Hugo Browne-Anderson"],
        "rss_feed": "https://feeds.fireside.fm/highsignal/rss",
    },
    {
        "id": "mlops_community",
        "name": "MLOps.community",
        "description": "Conversations about getting AI into production",
        "category": "interview",
        "release_schedule": "Weekly ish",
        "hosts": ["Demitrios Brinkmann"],
        "rss_feed": "https://anchor.fm/s/174cb1b8/podcast/rss",
    },
    {
        "id": "eye_on_ai",
        "name": "Eye on AI",
        "description": "Tracks new developments in AI research",
        "category": "interview",
        "release_schedule": "Weekly ish",
        "hosts": ["Craig S. Smith"],
        "rss_feed": "https://aneyeonai.libsyn.com/rss",
    },
    {
        "id": "datatalks_club",
        "name": "DataTalks.Club",
        "description": "Global online community of data professionals, ML engineers, AI practitioners",
        "category": "interview",
        "release_schedule": "Weekly on Fridays",
        "hosts": ["Slawomir Tulski"],
        "rss_feed": "https://anchor.fm/s/41286f68/podcast/rss",
    },

# news ------------------------------------------------
    {
        "id": "ai_policy_podcast",
        "name": "The AI Policy Podcast",
        "description": "Discussions on AI governance, regulation and policy",
        "category": "news",
        "hosts": ["Gregory C. Allen"],
        "rss_feed": "https://feeds.megaphone.fm/CSIS8973369418",
    },
    {
        "id": "ai_daily_brief",
        "name": "The AI Daily Brief: Artificial Intelligence News and Analysis",
        "description": "Biggest stories in AI and new AI tools/systems",
        "category": "news",
        "release_schedule": "Daily ish",
        "hosts": ["Nathaniel Whittemore"],
        "rss_feed": "https://anchor.fm/s/f7cac464/podcast/rss",
    },
    {
        "id": "last_week_in_ai",
        "name": "Last Week in AI",
        "description": "Weekly roundup of the biggest AI news stories",
        "category": "news",
        "release_schedule": "Every couple days",
        "hosts": ["Jeremie Harris", "Aundrey Kurenkov"],
        "rss_feed": "https://rss.art19.com/last-week-in-ai",
    },
    {
        "id": "ai_for_humans",
        "name": "AI For Humans: Weekly AI News, Tools & Trends",
        "description": "Comedy take on AI news, tools, and breakthroughs",
        "category": "news",
        "release_schedule": "Weekly on Friday",
        "hosts": ["Kevin Pereira", "Gavin Purcell"],
        "rss_feed": "https://rss.libsyn.com/shows/469701/destinations/3976203.xml",
    },
    {
        "id": "hard_fork",
        "name": "Hard Fork",
        "description": "Weekly tech and AI news by NYT tech journalists",
        "category": "news",
        "release_schedule": "Weekly on Friday",
        "hosts": ["Kevin Roose", "Casey Newton"],
        "rss_feed": "https://feeds.simplecast.com/l2i9YnTd",
    },
]

# lookups
INTERVIEW_PODCASTS = [p for p in PODCASTS if p["category"] == "interview"]
NEWS_PODCASTS = [p for p in PODCASTS if p["category"] == "news"]


# podcasts to fetch descriptions from for dad recommendation section
# descriptions only, fetched directly from RSS at digest time, not transcribed or embedded
# hard fork included above and here - tech and politics angle
DAD_PODCASTS = [
    {
        "id": "hard_fork_dad",
        "name": "Hard Fork",
        "description": "Weekly tech and AI news by tech journalists",
        "release_schedule": "Weekly on Friday",
        "hosts": ["Kevin Roose", "Casey Newton"],
        "rss_feed": "https://feeds.simplecast.com/l2i9YnTd",
    },
    {
        "id": "the_daily",
        "name": "The Daily",
        "description": "Daily news stories",
        "release_schedule": "Daily",
        "hosts": ["Michael Barbaro", "Rachel Abrams", "Natalie Kitroeff"],
        "rss_feed": "https://feeds.simplecast.com/Sl5CSM3S",
    },
    {
        "id": "strict_scrutiny",
        "name": "Strict Scrutiny",
        "description": "About the US Supreme Court and the legal culture that surrounds it",
        "release_schedule": "Weekly on Monday",
        "hosts": ["Leah Litman", "Kate Shaw", "Melissa Murray"],
        "rss_feed": "https://audioboom.com/channels/5166629.rss",
    },
    {
        "id": "ezra_klein_show",
        "name": "The Ezra Klein Show",
        "description": "Political opinions and long-form interviews on politics, policy, and ideas",
        "release_schedule": "Biweekly on Tuesday and Friday",
        "hosts": ["Ezra Klein"],
        "rss_feed": "https://feeds.simplecast.com/kEKXbjuJ",
    },
]