# all podcast metadata (list of dicts)

PODCASTS = [
    {
        "id": "dataframed",
        "name": "DataFramed",
        "description": "Interviews with data professionals and leaders on AI and data topics",
        "category": "interview",
        "release_schedule": "Weekly on Monday",
        "hosts": ["Richie Cotton"],
        "rss_feed": "https://feeds.captivate.fm/dataframed/",
    },
    {
        "id": "how_i_ai",
        "name": "How I AI",
        "description": "Interviews with diverse guests (moms, CTOs, etc.) on how they personally use AI",
        "category": "interview",
        "release_schedule": "Weekly on Monday",
        "hosts": ["Claire Vo"],
        "rss_feed": "https://anchor.fm/s/1035b1568/podcast/rss",
    },
    {
        "id": "practical_ai",
        "name": "Practical AI",
        "description": "Interviews with AI professionals on a wide range of AI topics",
        "category": "interview",
        "release_schedule": "Weekly ish",
        "hosts": ["Chris Benson", "Daniel Whitenack"],
        "rss_feed": "https://changelog.com/practicalai/feed",
    },
    {
        "id": "women_in_data",
        "name": "Women in Data Podcast",
        "description": "Interviews with women in data on careers, being a woman in the field, and data & AI tips",
        "category": "interview",
        "release_schedule": "Biweekly",
        "hosts": ["Karen Jean-Francois"],
        "rss_feed": "https://feed.podbean.com/womenindata/feed.xml",
    },
    {
        "id": "twiml",
        "name": "The TWIML AI Podcast",
        "description": "Deep-dive interviews with AI/ML researchers and practitioners on cutting-edge topics",
        "category": "interview",
        "release_schedule": "Biweekly ish",
        "hosts": ["Sam Charrington"],
        "rss_feed": "https://twimlai.com/feed",
    },
    {
        "id": "super_data_science",
        "name": "Super Data Science: ML & AI Podcast with Jon Krohn",
        "description": "ML, AI, and data professionals on tools, techniques, and careers",
        "category": "interview",
        "release_schedule": "Weekly on Tuesday, Friday (short)",
        "hosts": ["Jon Krohn"],
        "rss_feed": "https://feeds.megaphone.fm/SUPERDATASCIENCEPTYLTD9836501887",
    },
    {
        "id": "latent_space",
        "name": "Latent Space: The AI Engineer Podcast",
        "description": "Technical deep dives with AI researchers and builders on models, agents, infra, and tools",
        "category": "interview",
        "release_schedule": "A couple times a week",
        "hosts": ["Shawn Wang", "Alessio Fanelli"],
        "rss_feed": "https://rss.flightcast.com/vgnxzgiwwzwke85ym53fjnzu",
    },
    {
        "id": "gradient_dissent",
        "name": "Gradient Dissent: Conversations on AI",
        "description": "Interviews with AI industry leaders on deploying ML in production, hosted by Weights & Biases",
        "category": "interview",
        "release_schedule": "Biweekly ish",
        "hosts": ["Lukas Biewald"],
        "rss_feed": "https://feeds.captivate.fm/gradient-dissent/",
    },
    {
        "id": "no_priors",
        "name": "No Priors: Artificial Intelligence",
        "description": "Interviews with top AI engineers, researchers and founders on AGI, market disruption, and the future of AI",
        "category": "interview",
        "release_schedule": "Weekly on Thursday",
        "hosts": ["Sarah Guo", "Elad Gil"],
        "rss_feed": "https://feeds.megaphone.fm/nopriors",
    },
    {
        "id": "mlst",
        "name": "Machine Learning Street Talk",
        "description": "Deep academic paper discussions and research interviews with ML researchers and PhDs",
        "category": "interview",
        "release_schedule": "Biweekly ish",
        "hosts": ["Tim Scarfe", "Keith Duggar"],
        "rss_feed": "https://anchor.fm/s/1e4a0eac/podcast/rss",
    },
    {
        "id": "ai_daily_brief",
        "name": "The AI Daily Brief: Artificial Intelligence News and Analysis",
        "description": "Biggest stories in AI and new AI tools/systems",
        "category": "news",
        "release_schedule": "Daily ish",
        "hosts": ["Nathaniel Whittemore"],
        "rss_feed": "https://anchor.fm/s/f7cac464/podcast/rss",
    },
    {
        "id": "last_week_in_ai",
        "name": "Last Week in AI",
        "description": "Weekly roundup of the biggest AI news stories",
        "category": "news",
        "release_schedule": "Every couple days",
        "hosts": ["Jeremie Harris", "Aundrey Kurenkov"],
        "rss_feed": "https://rss.art19.com/last-week-in-ai",
    },
    # {
    #     "id": "ai_for_humans",
    #     "name": "AI For Humans: Weekly AI News, Tools & Trends",
    #     "description": "Comedy take on AI news, tools, and breakthroughs",
    #     "category": "news",
    #     "release_schedule": "Weekly on Friday",
    #     "hosts": ["Kevin Pereira", "Gavin Purcell"],
    #     "rss_feed": "https://www.aiforhumans.show/api/linkblog/feed",
    # },
    {
        "id": "hard_fork",
        "name": "Hard Fork",
        "description": "Weekly tech and AI news by NYT tech journalists",
        "category": "news",
        "release_schedule": "Weekly on Friday",
        "hosts": ["Kevin Roose", "Casey Newton"],
        "rss_feed": "https://feeds.simplecast.com/l2i9YnTd",
    },
]

# lookups
INTERVIEW_PODCASTS = [p for p in PODCASTS if p["category"] == "interview"]
NEWS_PODCASTS = [p for p in PODCASTS if p["category"] == "news"]
PODCASTS = [p for p in PODCASTS if p["id"] == "hard_fork"]  # TEMP: only fetch hard fork for now